name = "Nyan Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3917e75b1abba8284ad7d78ac57aacbe6ec3d7b21ca8d7757e453fcc00c5cd3c"

[versions]
forge = "36.0.0"
minecraft = "1.16.5"
