name = "Nyan Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e32dccf759507eb2dfbd3d549b74eae1f1b37679806fa297f5b1bc1f0846584a"

[versions]
forge = "36.0.0"
minecraft = "1.16.5"
