name = "Nyan Craft"
author = "Beri"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e1a8377f5328f7b97ebd96b920c6bdafc34b756616ff25d4cc746d081db648d"

[versions]
forge = "36.2.0"
minecraft = "1.16.5"
