name = "AmbientSounds 4"
filename = "AmbientSounds_v3.1.10_mc1.16.5.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3504/112/AmbientSounds_v3.1.10_mc1.16.5.jar"
hash-format = "murmur2"
hash = "3261711247"

[update]
[update.curseforge]
file-id = 3504112
project-id = 254284
release-channel = "beta"
