name = "LevelHearts"
filename = "levelhearts-1.16.2-2.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3042/439/levelhearts-1.16.2-2.2.0.jar"
hash-format = "murmur2"
hash = "1694444254"

[update]
[update.curseforge]
file-id = 3042439
project-id = 273640
release-channel = "beta"
