name = "Macaw's Bridges"
filename = "mcw-bridges-1.0.6-mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3378/577/mcw-bridges-1.0.6-mc1.16.5.jar"
hash-format = "murmur2"
hash = "1318984277"

[update]
[update.curseforge]
file-id = 3378577
project-id = 351725
release-channel = "beta"
