name = "MineColonies"
filename = "minecolonies-1.0.85-ALPHA-universal.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3504/489/minecolonies-1.0.85-ALPHA-universal.jar"
hash-format = "murmur2"
hash = "498144928"

[update]
[update.curseforge]
file-id = 3504489
project-id = 245506
release-channel = "beta"
